name: Test

on:
  push:
    branches: [Branch2]

jobs:
  firstJob:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v3
    - name: Run script
      run: |
        pwd
        npm install -g bats
        bash ./CloudOps/Test.sh
        
