name: Test

on:
  push:
    branches: [Branch2]

jobs:
  firstJob:
    runs-on: [self-hosted, linux, x64]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run script
      run: |
        pwd
        bash ./CloudOps/Test.sh
        echo "This is a new file" >> newfile.txt
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Newfile
        path: ./newfile.txt
  secondJob:
    runs-on: [self-hosted, linux, x64]
    steps:
    - name: Setup node
      uses: actions/setup-node@v3
    - run: |
        npm install -g bats
        bats -v
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: Newfile
    - run: |
        ls
        cat newfile.txt
